version: "2"
services:
  whe:
    image: wihajster:0.0.0
    command: sh -c "/opt/jboss/wildfly/bin/standalone.sh -b 0.0.0.0 -bmanagement 0.0.0.0 --debug *:8787"
    ports:
      - "8080:8080"
      - "9990:9990"
      - "8787:8787"
    links:
      - "db:database"
  db:
    image: postgres:16.1
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
